version: '3.2'

services:
  dev-node:
    image: local/standalone-node
    build:
      context: https://github.com/KILTprotocol/kilt-node.git
      cache_from:
        - kiltprotocol/standalone-node
        - local/standalone-node
