name: Do stuff

on: [push]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          echo "├─ yargs-parser@npm:20.2.7
          ├─ yargs-parser@npm:20.2.9
          ├─ yargs@npm:16.2.0" > locked_dependencies.txt
      - name: stuff
        run: |
          echo 'DEPS<<EOF' >> $GITHUB_ENV
          cat locked_dependencies.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - run: echo ${{ env.DEPS }}
      - name: issue-bot
        uses: imjohnbo/issue-bot@v3
        with:
          labels: 'bug, incompatible dependencies, automation'
          pinned: false
          close-previous: true
          linked-comments: true
          title: SDK no longer compatible with latest dependecies
          body: |-
            ## Incompatibilities detected

            A scheduled test workflow using the latest available dependencies matching our semver ranges has failed.
            We may need to constrain dependency ranges in our `package.json` or introduce fixes to recover compatibility.
            Below you can find a summary of depedency versions against which these tests were run.

            _Note: This issue was **automatically created** as a result of scheduled CI tests on ${{ env.TODAY }}._

            <details>
              <summary>Dependency versions</summary>

              ${{ env.DEPS }}
            </details>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
