name: Dispatch test on docs repo
on:
  repository_dispatch:
  push:
    tags:
      - '*'
jobs:
  releaseTagEvent:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previousTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.27.0
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: KILTprotocol/docs
          event-type: sdk-update
          client-payload: '{"previousTag": "${{ steps.previousTag.outputs.tag }}",{"latestTag": "${{github.ref_name}}"}'
