name: Dispatch test on docs repo
on:
  repository_dispatch:
    types: [dispatch-test]
  push:
    branches:
      - test-docs
jobs:
  releaseTagEvent:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.27.0
      - name: Get the latest tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
